[project]
name = "resolutionhelper"
description = "Resolution Picker and Calculator"
version = "1.0.3"
license = "MIT"
dependencies = [] 

[project.urls]
Repository = "https://github.com/AlfredSartan572/ComfyUI-ResolutionHelper"

[tool.comfy]
PublisherId = "alfredsartan572"
DisplayName = "ComfyUI-ResolutionHelper"
Icon = ""
includes = []
